### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by BenjaminBeguin** [BenjaminBeguin/tesla#3]
Revoir header par rapport au maquettes (background sur les icone ;) )

**Comment by Calderis** [comment]
Pour les hexagones : les bords sont arrondies
Réglages des couleurs entre activé/non activé

Il manque le nom "Tesla"

Impossible de fixer un gradient sur les hexagones...

**Comment by Calderis** [comment]
les boutons sont devenu des images. Je ferme
